### ISSUE TITLE
基于webpack打包的就不能用呀了是吗，遇到了一样的问题 好急。。

### ISSUE THREAD

**Issue by koiomi** [b2nil/taro-plugin-vue#1]
hihi，我用Taro脚手架初始化的项目，相关配置应该是webpack打包的 。或者我能加点什么代码弄好吗？

**Comment by b2nil** [comment]
这是 Vite 的插件，不能用于 webpack，而且这个插件主要用于构建第三方组件。
用 webpack 的话，可以直接配置 vue-loader。
